-- 코드를 작성해주세요
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT CHILD.ID
                    FROM ECOLI_DATA CHILD INNER JOIN ECOLI_DATA PARENT ON CHILD.PARENT_ID = PARENT.ID
                    WHERE PARENT.PARENT_ID IS NULL)
ORDER BY ID;