-- 코드를 입력하세요
SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
INNER JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE (CRCC.CAR_TYPE = '세단' OR CRCC.CAR_TYPE = 'SUV') AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) BETWEEN 500000 AND 2000000
GROUP BY CRCRH.CAR_ID
HAVING MIN(START_DATE) > '2022-11-30' OR MAX(END_DATE) < '2022-11-01'
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC;