-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PURCHASED_USERS, 
ROUND(COUNT(DISTINCT USER_ID) / (
    SELECT COUNT(DISTINCT USER_ID)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), 1) PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
GROUP BY YEAR, MONTH