-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (1 - IFNULL(DISCOUNT_RATE, 0) / 100)) FEE
FROM (
    SELECT *, (
        CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        END
    ) DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) CRCRH JOIN CAR_RENTAL_COMPANY_CAR CRCC
ON CRCRH.CAR_ID = CRCC.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON CRCDP.DURATION_TYPE = CRCRH.DURATION_TYPE AND CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;