-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND(DAILY_FEE * DURATION * (1 - DISCOUNT_RATE / 100)) FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC JOIN
(SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 DURATION, 0 DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE HISTORY_ID NOT IN (
    SELECT HISTORY_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        END = DURATION_TYPE
    WHERE CAR_TYPE = '트럭'
)
UNION
SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 DURATION, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
    END = DURATION_TYPE
WHERE CAR_TYPE = '트럭') CC
ON CRCC.CAR_ID = CC.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;