-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) SUM_TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR) FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) SUM_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.SUM_TOTAL_ORDER + J.SUM_TOTAL_ORDER DESC LIMIT 3;