-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, P.PT_NO AS PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT AS P INNER JOIN DOCTOR AS D INNER JOIN APPOINTMENT AS A
ON P.PT_NO = A.PT_NO AND D.DR_ID = A.MDDR_ID
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;