-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME_TABLE
    WHERE HOUR < 23
)

SELECT TT.HOUR, IFNULL(COUNT, 0) AS COUNT
FROM TIME_TABLE AS TT LEFT OUTER JOIN (
    SELECT HOUR(DATETIME) AS HD, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)    
) AS AO ON TT.HOUR = AO.HD
ORDER BY TT.HOUR;

