-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (ED2.MS - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA AS ED INNER JOIN (SELECT MAX(SIZE_OF_COLONY) AS MS, YEAR(DIFFERENTIATION_DATE) AS YEAR
                                    FROM ECOLI_DATA
                                    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS ED2
ON YEAR(ED.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR, YEAR_DEV;