SELECT YEAR(ED1.DIFFERENTIATION_DATE) YEAR, (ED2.M - ED1.SIZE_OF_COLONY) YEAR_DEV, ID
FROM ECOLI_DATA ED1 INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) Y, MAX(SIZE_OF_COLONY) M
    FROM ECOLI_DATA
    GROUP BY Y
) ED2 ON YEAR(ED1.DIFFERENTIATION_DATE) = ED2.Y
ORDER BY YEAR, YEAR_DEV;